language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g phantomjs
  - npm install -g grunt-cli
  - ./node_modules/.bin/bower -V install
script: "grunt test"
branches:
  except:
    - 1.0
    - 1.1
    - gh-pages
